    <form action="<?php echo $action; ?>" method="<?php echo $method; ?>">
        <table>
            <tr>
                <td>
                    <?php echo $username_label . PHP_EOL; ?>
                </td>
                <td>
                    <?php echo $username . PHP_EOL; ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?php echo $email_label . PHP_EOL; ?>
                </td>
                <td>
                    <?php echo $email . PHP_EOL; ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?php echo $password_label . PHP_EOL; ?>
                </td>
                <td>
                    <?php echo $password . PHP_EOL; ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?php echo $checkbox_colors_label . PHP_EOL; ?>
                </td>
                <td>
                    <?php echo $checkbox_colors . PHP_EOL; ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?php echo $radio_colors_label . PHP_EOL; ?>
                </td>
                <td>
                    <?php echo $radio_colors . PHP_EOL; ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?php echo $select_colors_label . PHP_EOL; ?>
                </td>
                <td>
                    <?php echo $select_colors . PHP_EOL; ?>
                </td>
            </tr>
            <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    <?php echo $submit . PHP_EOL; ?>
                </td>
            </tr>
        </table>
    </form>