#!/bin/bash
#
# Pop PHP Framework BASH CLI script (http://www.popphp.org/)
# https://github.com/nicksagona/PopPHP
# http://www.popphp.org/license    New BSD License
#
# Possible arguments
#
# -c --check                     Check the current configuration for required dependencies
# -h --help                      Display this help
# -i --install file.php          Install a project based on the install file specified
# -l --lang fr                   Set the default language for the project
# -m --map folder file.php       Create a class map file from the source folder and save to the output file
# -s --show                      Show project install instructions
# -v --version                   Display version of Pop PHP Framework
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
CYG_PATH="$( which cygpath 2> /dev/null )"

if [ "$CYG_PATH" != "" ]; then
    SCRIPT_PATH="$( cygpath -w $SCRIPT_DIR )\\pop.php $@"
    SCRIPT_PATH=${SCRIPT_PATH//\\/\/}
else
    SCRIPT_PATH="$SCRIPT_DIR/pop.php $@"
fi
php $SCRIPT_PATH
