#!/bin/bash
#
# Pop PHP Framework BASH CLI script
#
# LICENSE
#
# This source file is subject to the new BSD license that is bundled
# with this package in the file LICENSE.TXT.
# It is also available through the world-wide-web at this URL:
# http://www.popphp.org/LICENSE.TXT
# If you did not receive a copy of the license and are unable to
# obtain it through the world-wide-web, please send an email
# to info@popphp.org so we can send you a copy immediately.
#
# Possible arguments
#
# -b --build      Build a project based on the project configuration file
# -c --check      Check the current configuration for required dependencies
# -h --help       Display this help
# -v --version    Display version of Pop PHP Framework
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TEMP=`getopt -o bchv --long build,check,help,version -n 'Error' -- "$@"`

if [ $# = 0 ] ; then echo -e "\nPop PHP Framework CLI script\n============================\n\nYou must pass at least one argument.\nRun './pop -h' for help.\n" >&2 ; exit 1 ; fi

eval set -- "$TEMP"

while true ; do
    case "$1" in
        -b|--build) echo -e "$("$DIR"/pop.php -b)\n" ; shift ;;
        -c|--check) echo -e "$("$DIR"/pop.php -c)\n" ; shift ;;
        -h|--help) echo -e "$("$DIR"/pop.php -h)\n" ; shift ;;
        -v|--version) echo -e "$("$DIR"/pop.php -v)\n" ; shift ;;
        *) break ;;
    esac
done