#!/bin/bash
#
# Pop PHP Framework BASH CLI script
#
# LICENSE
#
# This source file is subject to the new BSD license that is bundled
# with this package in the file LICENSE.TXT.
# It is also available through the world-wide-web at this URL:
# http://www.popphp.org/LICENSE.TXT
# If you did not receive a copy of the license and are unable to
# obtain it through the world-wide-web, please send an email
# to info@popphp.org so we can send you a copy immediately.
#
# Possible arguments
#
# -b --build ProjectName    Build a project based on the files in the 'config' folder
# -c --check                Check the current configuration for required dependencies
# -h --help                 Display this help
# -i --instructions         Display build project instructions
# -l --lang fr              Set the default language for the project
# -m --map folder file.php  Create a class map file from the source folder and save to the output file
# -t --test folder          Run the unit tests from a folder
# -v --version              Display version of Pop PHP Framework
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TEST_DIR=

if [ "$1" == "-t" ] || [ "$1" == "--test" ]; then
    if [ "$2" != "" ]; then
        if [ ! -d "$2" ]; then
            echo -e "The folder '$2' does not exist.\n"
            exit 1
        else
            TEST_DIR="$2"
        fi
    else
        TEST_DIR="$SCRIPT_DIR/../vendor/PopPHPFramework/tests/Pop"
    fi
    echo -e "Testing folder '$TEST_DIR'...\n"
    phpunit "$TEST_DIR"
else
    "$SCRIPT_DIR"/pop.php "$1" "$2" "$3"
fi
